compressionLevel: mixed

enableGlobalCache: false

# Make Yarn install into node_modules so npm commands like `npm outdated`
# can detect installed packages. This disables Plug'n'Play for this project.
nodeLinker: node-modules
